test_app_hash:
  build: .
  dockerfile: test_app.dockerfile
  ports:
   - "9000:9000"
  environment:
    APP_PORT: 9000
    CONFIG_HASH: 1

test_app_path:
  build: .
  dockerfile: test_app.dockerfile
  ports:
   - "9001:9001"
  environment:
    APP_PORT: 9001
    CONFIG_HASH: 0

test_app_basepath:
  build: .
  dockerfile: test_app.dockerfile
  ports:
   - "9002:9002"
  environment:
    APP_PORT: 9002
    CONFIG_HASH: 0
    CONFIG_BASEPATH: '/app'

example_basic:
  build: .
  dockerfile: example_basic.dockerfile
  command: elm make Main.elm

example_full:
  build: .
  dockerfile: example_full.dockerfile
  command: elm make ./src/Main.elm

webdriver:
  image: selenium/standalone-chrome
  links:
    - test_app_hash
    - test_app_path
    - test_app_basepath
  ports:
    - "4444:4444"

test_unit:
  image: sporto/elm-node-webpack
  volumes:
    - .:/usr/src
  working_dir: /usr/src
  command: ./start_test_unit.sh

test_app_integration:
  build: ./test/integration
  links:
    - test_app_hash
    - test_app_path
    - test_app_basepath
    - webdriver
  volumes:
    - ./test/integration:/usr/src
  working_dir: /usr/src
  command: ./run_tests.sh
  environment:
    WEBDRIVER_HOST: webdriver
    WEBDRIVER_PORT: 4444
    WEBDRIVER_BROWSER: chrome
